- .gitignore
- README.md
- data/README.md
- infra/base/main.tf
- infra/base/variables.tf
- infra/main.tf
Bring project infra under Terraform control (closes #2)
> Brings infra under terrafrom control

- .github/workflows/on-push.yml
- .github/workflows/scheduled.yml
- README.md
- data/fetch_raw.sh
- data/raw/leagues.json
- dvc.lock
- prep/asset_runner.py
- prep/assets/appearances.py
- prep/assets/base.py
- prep/assets/clubs.py
- prep/assets/leagues.py
Fix last two [failing](https://github.com/dcaribou/player-scores/actions/runs/700235413) scheduled runs
> Fix scheduled run

- dvc.lock
- dvc.yaml
- prep/asset_runner.py
- prep/assets/players.py
Adds `players` as a new dataset asset in the. The `players` asset contains all players in clubs in scope, with one row per player.
> Add new asset: players

- README.md
- data/fetch_raw.sh
- dvc.lock
- dvc.yaml
- environment.yml
- prep/asset_runner.py
- prep/assets/appearances.py
- prep/assets/games.py
- prep/assets/players.py
- prep/datapackage_description.md
- prep/prep.ipynb
- sync.py
* Add games asset
* Refactor DVC data pipeline
* Move to DVC 2.0.1
* Move game attributes from appearances to games
> Add games asset and refactor

- dvc.lock
- prep/asset_runner.py
- prep/assets/base.py
- prep/assets/clubs.py
- prep/assets/players.py
- prep/checks.py
> Decode UTF-8 characters from names parsed from URLs

- dvc.lock
- environment.yml
- prep/assets/base.py
- prep/assets/clubs.py
- prep/assets/games.py
- prep/assets/players.py
- prep/checks.py
- sync.py
* Clubs
* `pretty_name`
* Games
* `league_code`
* Players
* `height_in_cm`
* `foot`
* `sub_position`
* `position`
* `date_of_birth`
* `country_of_citizenship`
* `country_of_birth`
* `pretty_name`
> Add attributes to datasets

- .github/workflows/on-schedule.yml
> Fix `token` workflow variable assignment

- README.md
> Document process to self-grant access to DVC storage

- prep/asset_runner.py
- prep/datapackage_description.md
A couple of updates on the dataset docs and summary
> Update dataset docs and summary

- data/prep.dvc
- data/raw.dvc
- prep/datapackage_description.md
Add historical data from season 2016-2017
Relates to #12
> Add historical data: season 2015-2016

- .github/workflows/on-push.yml
- 1_acquire.py
- README.md
- data/raw.dvc
- prep/asset_runner.py
- prep/assets/players.py
Due to some changes in transfermarkt the scraper code (covered in the issue https://github.com/dcaribou/transfermarkt-scraper/issues/29) needed to be updated to scrape player attributes correctly. This PR updates the data processing code to deal with the a couple if small changes in the scraper output due to the aforementioned change.
**Bonus**: Enable CI builds to run on PRs
> Adapt to scraper changes on `players` crawler

- 2_prepare.py
- 3_sync.py
- prep/.gitignore
- prep/asset_runner.py
- prep/assets/base.py
- prep/assets/games.py
The previous structure of AssetRunner did not allow defining frictionless constrains at resource level. This is a refactor for supporting defining resource constrains in the future.
> Support data validations at "resource" level

- data/prep.dvc
- data/raw.dvc
- prep/datapackage_description.md
Add historical data from season 2014-2015
Relates to #12
> Add historical data: season 2014-2015

- data/prep.dvc
- prep/asset_runner.py
- prep/assets/base.py
- prep/assets/player_valuations.py
- prep/assets/players.py
- prep/assets/utils.py
- prep/config.yml
- prep/datapackage_description.md
Bonus: Add support for frictionless checks
> Add historical data: seasons 2012-2014

- 1_acquire.py
> Fix current/max market value in players

- infra/main.tf
> Add iam user to whitelist

- data/prep.dvc
- transfermarkt_datasets/assets/players.py
> Add agent name to `players` asset

- 1_acquire.py
- cloud_lib.py
- data/prep.dvc
- data/raw.dvc
- transfermarkt_datasets/assets/players.py
- transfermarkt_datasets/checks.py
Closes #100 , see further details in the issue.
**Bonus**
* Increase timeout of aws batch job
* Improve `too-many-missings` error message
> Add image URL to `players` asset

- data/prep.dvc
- poetry.lock
Hoping this will help addressing the latest pipeline failures.
> Update pip dependencies

- Makefile
- data/prep.dvc
- transfermarkt_datasets/assets/base_players.py
- transfermarkt_datasets/assets/cur_players.py
> Add contract expiration date to `players`

- data/prep.dvc
- transfermarkt_datasets/assets/base_players.py
- transfermarkt_datasets/assets/cur_players.py
> Add city of birth to the players asset

- .github/workflows/on-push.yml
- .github/workflows/on-schedule.yml
- data/prep.dvc
- data/raw.dvc
Both the `build` and the `pipeline` are failing.
> Fix github actions failures

- Dockerfile
- data/prep.dvc
- data/raw.dvc
- transfermarkt_datasets/assets/base_game_events.py
> Add add new asset `game_events`

- data/raw.dvc
- pyproject.toml
- streamlit/01_👋_about.py
- streamlit/pages/03_📈_analysis:_player_value.py
- transfermarkt_datasets/assets/base_player_valuations.py
- transfermarkt_datasets/assets/base_players.py
- transfermarkt_datasets/assets/cur_player_valuations.py
- transfermarkt_datasets/assets/cur_players.py
- transfermarkt_datasets/core/utils.py
> Rename market value columns: `_gbp` to `_eur`

- .github/workflows/deploy-streamlit.yml
- .streamlit/config.toml
- Makefile
> Deploy to fly.io automatically

- .gitignore
- config.yml
- poetry.lock
- pyproject.toml
- scripts/acquire.py
- streamlit/pages/02_🔎_explore.py
Reverts dcaribou/transfermarkt-datasets#150
> Revert "Centralize logging configuration for acquiring"

- .github/workflows/on-push.yml
- README.md
- data/README.md
- poetry.lock
- pyproject.toml
- streamlit/utils.py
Closes #155 
**Bonus** &rarr; Modify commit message of CI job to be consitent
> Upgrade streamlit to 1.22.0

- .github/FUNDING.yml
Display the sponsors button in the repo to allow users sponsoring the project.
> Setup sponsors button

- .github/workflows/on-push.yml
- .gitignore
- README.md
- config.yml
- data/prep.dvc
- data/raw.dvc
- dbt/models/base/base_appearances.sql
- dbt/models/curated/models.yml
- notebooks/chat_playbook.ipynb
- poetry.lock
- pyproject.toml
- scripts/acquire.py
- streamlit/pages/02_🔎_explore.py
- transfermarkt_datasets/core/asset.py
Fix various DQ issues
- 'null' string present in club names
- appearances without a game
**Bouns**
* Sample notebook for querying the dataset with natural language powered by OpenAI APIs 🚀 
* Add configuration options for acquiring step
* Closes #169
* Closes #149
> Fix various DQ issues

- Makefile
- README.md
- config.yml
- dbt/models/curated/game_events.sql
- poetry.lock
- scripts/acquire.py
> Handle compressed files natively in scraper

- README.md
- streamlit/01_👋_about.py
- streamlit/pages/02_🔎_explore.py
Adds a FAQs link and general community guidelines to the readme to address common questions.
> [skip ci] Add FAQs link to README

- fly.toml
> Migrate fly.io app to V2

- infra/main.tf
Thank you for this project!  I'm looking forward to exploring
> Add new iam user

- .github/workflows/on-schedule.yml
- Makefile
- README.md
- config.yml
- data/prep.dvc
- data/raw.dvc
- dbt/models/curated/models.yml
- streamlit/pages/04_📈_analysis:_manager_performance.py
Season 2022 is closed. This PR sets up the project to start fetching data for season 2023.
Relates to #12
> Switch scraper season to 2023

- .github/workflows/on-push.yml
- Makefile
- data/prep.dvc
- data/raw.dvc
- dbt/dbt_project.yml
- dbt/macros/io.sql
- dbt/models/curated/game_events.sql
- dbt/models/curated/models.yml
- dbt/packages.yml
- dbt/profiles.yml
- poetry.lock
- pyproject.toml
- scripts/acquire.py
Reported [here](https://www.kaggle.com/datasets/davidcariboo/player-scores/discussion/429172).
* General upgrade of all python dependencies.
* Adds data-diff and related config to test differences between models (dev vs prod). Related #185
> Fix missing appearances from season 2022

- data/prep.dvc
- dbt/models/base/base_player_valuations.sql
- dbt/models/curated/models.yml
> Remove outlier in player valuations

- README.md
- data/prep.dvc
- poetry.lock
- transfermarkt_datasets/datapackage_description.md
Closes #192, #198
**Bonus**
- Update dbt (minor) version
> Improve README and frontend guidelines

- .github/workflows/deploy-streamlit.yml
> Fix GA streamlit deploy

- README.md
Some links where broken due to some recent changes in headers and anchors.
> [skip ci] Fix links to sections in README

- .devcontainer/devcontainer.json
- README.md
Setup Github codespaces in the repo.
> Setup codespaces

- data/prep.dvc
- data/raw.dvc
> Restore players file to its latest healthy version

- data/prep.dvc
- data/raw.dvc
- dbt/models/curated/game_events.sql
* Syntax error on game_events model
* Updated raw data to contain the new attributes
> Fixes on the game events (followup to #217)

- .github/workflows/on-schedule.yml
> [skip ci] Increase pipeline frequency

- data/prep.dvc
- data/raw.dvc
- dbt/models/curated/models.yml
> Refresh data for seasons 13 and 12

- data/prep.dvc
- dbt/models/curated/game_events.sql
- transfermarkt_datasets/assets/cur_game_events.py
> Add a documentation for `game_events`

- data/prep.dvc
- dbt/models/curated/players.sql
- poetry.lock
- pyproject.toml
Fixes #235
Essentially, the reason why the pipeline fails on this test is due to some change on transfermarkt HTMK (https://github.com/dcaribou/transfermarkt-scraper/issues/73)
Since player attributes are changing unfrequently, this PR disables the updates on the player model so it so the pipeline can proceed.
> Dbt test `too_many_missings_players_market_value_in_eur__0_38` is faling

- .github/workflows/sync-dataworld.yml
- .github/workflows/sync-kaggle.yml
- .github/workflows/sync-streamlit.yml
- Dockerfile
- Makefile
> Fix sync failures due to local .git directory missing

- data/prep.dvc
- data/raw/transfermarkt-scraper.dvc
- dbt/models/curated/models.yml
- poetry.lock
> Fix missing `date_of_birth` in `players` asset

- .github/workflows/build.yml
> Avoid colliding builds after acquisition

- .github/workflows/build.yml
> Skip build-image for data changes

- .github/workflows/acquire-transfermarkt-scraper.yml
- .github/workflows/build.yml
- dbt/models/curated/models.yml
- poetry.lock
> Fix bug on appearances scraping

- data/prep.dvc
- dbt/models/base/transfermarkt_api/base_market_value_development.sql
- dbt/models/curated/models.yml
- dbt/models/curated/player_valuations.sql
- transfermarkt_datasets/assets/cur_player_valuations.py
Fixes #275
* Remove redundant columns from `player_valuations`
> Fix failing test `...max_to_be_between_player_valuations_datetime___2023_12_31`

- data/prep.dvc
- data/raw/transfermarkt-scraper.dvc
- dbt/models/curated/models.yml
- poetry.lock
> Restore `game_lineups` updates

- .github/workflows/acquire-transfermarkt-api.yml
- .github/workflows/acquire-transfermarkt-scraper.yml
- Makefile
- README.md
- config.yml
- data/prep.dvc
- data/raw/transfermarkt-api.dvc
- data/raw/transfermarkt-scraper.dvc
- dbt/macros/parsing.sql
- dbt/models/curated/models.yml
- dbt/tests/consistent_number_of_games_per_matchday.sql
- scripts/acquiring/transfermarkt-api.py
- scripts/acquiring/transfermarkt-scraper.py
- streamlit/pages/04_📈_app:_manager_performance.py
> Switch scraper to season 2024
