dcaribou/transfermarkt-datasets

.github/workflows/scheduled.yml
.gitignore
data/fetch_raw.sh
dvc.lock
prep/asset_runner.py
prep/assets/appearances.py
prep/assets/base.py

Push to a S3 a copy of scrapy cache after every run. This will enable historical backfilling if the site changes over time, and storing the `.json` semi-raw files  will no longer be necessary
~~**A new scraper release is necessary** for this changes to work (v0.1.1)~~

Save a copy of scrapy cache on every run

---

.github/workflows/on-schedule.yml
data/prep.dvc
prep/assets/clubs.py

a different (personal access) github token need to be setup here so that a 'add-and-commit' step below triggers the 'on-push' workflow
checkout https://github.community/t/push-from-action-does-not-trigger-subsequent-action/16854
Bonus: remove useless column in clubs

Use separate access token for 'on-schedule' workflow

---

.gitignore
infra/base/main.tf
infra/base/variables.tf
infra/main.tf

In order to be able to pull data from DVC remote storage, potential contributors need to be able to List and Get objects from S3 bucket s3://player-scores. Enable users to self-grant permissions for this actions by creating a PR adding their IAM user to a whitelist in the Terraform configuration.
Closes #44

Enable self-serve DVC backend access granting

---

infra/main.tf

This PR adds the project IAM process user ARN to the list of ARNs whitelisted for DVC access (read and list).
This PR may be used as reference for granting access to DVC to other IAM users. Self-serve access to the DVC remote storage for this project by creating an analogous PR, adding the ARN of your users to the `authorized_users` list.

Add `player-scores` IAM user ARN to DVC whitelist

---

.dvc/config
.github/workflows/on-push.yml
.github/workflows/on-schedule.yml
1_acquire.py
3_sync.py
README.md
environment.yml
infra/main.tf
notebooks/prep_playbook.ipynb
prep/datapackage_description.md

Rename repository as `transfermarkt-datasets`

---

3_sync.py
README.md
data/prep.dvc
data/raw.dvc
notebooks/prep_playbook.ipynb
prep/assets/appearances.py
prep/assets/games.py
prep/datapackage_description.md

New fields added to `games` asset
* `time`
* `home_club_position` and `away_club_position`
* `attendance`
* `stadium`
Additionally, the `url` is removed from the appearances, as it's very repetitive and similar to the URL included in `players`.
- Make a local copy of 'games' assets
- DVC pull
- Replace all but current seasons with local copy
- Re run the pipeline + check
- Commit and merge

Add new fields to `games` asset

---

prep/assets/base.py
prep/assets/clubs.py

Fixes #58 
Update deduping to keep last asset version across seasons. Prior to this change, the first version was kept in the prep assets.

Fix: keep last asset version on deduping

---

2_prepare.py
data/prep.dvc
data/raw.dvc
prep/asset_runner.py
prep/assets/games.py
prep/assets/players.py

* Add `referee` to `games`' asset (closes #57)
* Add `market_value_in_gbp` and `highest_market_value_in_gbp` to `players`' asset (contributed to the scraper [here](https://github.com/dcaribou/transfermarkt-scraper/pull/32), thanks @DonFloriano27)
* **Bonus**: Support a `--season` argument to the prep script for building assets using raw data from a single season

Add referee and market value to datasets

---

2_prepare.py
data/prep.dvc
infra/batch/batch.tf

Bumping max and current memory resources for prep step, as the current cap at 16GB is not enough.

Add more resources to prep step

---

data/prep.dvc
poetry.lock
pyproject.toml
streamlit/markdown_blocks/analysis/analysis_manager_performance.md
streamlit/pages/02_🔎_explore.py
streamlit/pages/04_📈_analysis:_manager_performance.py
streamlit/utils.py
transfermarkt_datasets/assets/base_appearances.py
transfermarkt_datasets/assets/base_clubs.py
transfermarkt_datasets/assets/base_competitions.py
transfermarkt_datasets/assets/base_games.py
transfermarkt_datasets/assets/base_player_valuations.py
transfermarkt_datasets/assets/base_players.py
transfermarkt_datasets/assets/cur_appearances.py
transfermarkt_datasets/assets/cur_club_games.py
transfermarkt_datasets/assets/cur_clubs.py
transfermarkt_datasets/assets/cur_competitions.py
transfermarkt_datasets/assets/cur_games.py
transfermarkt_datasets/assets/cur_player_valuations.py
transfermarkt_datasets/assets/cur_players.py
transfermarkt_datasets/core/asset.py
transfermarkt_datasets/core/dataset.py
transfermarkt_datasets/core/schema.py
transfermarkt_datasets/core/utils.py
transfermarkt_datasets/tests/test_assets.py
transfermarkt_datasets/tests/test_dataset.py
transfermarkt_datasets/tests/test_schema.py

Add a radar / polar graph comparator for manager performance in `04_📈_analysis:_manager_performance.py`. Such graph is helpful for comparing a manager performance to other managers across different competitions.
Closes #110 
* Add an asset schema tab in the explore page
* Improve exploration

Add radar-type comparator to manager perf analysis

---

.github/workflows/on-schedule.yml
.gitmodules
1_acquire.py
README.md
bootstrap.sh
pyproject.toml

Rather than using a submodule, let's take advantage of poetry to define `transfermarkt-scraper` as a dependency.

Add `transfermarkt-scraper` as poetry dependency

---

.github/workflows/on-push.yml

Pulling the whole data folder during all CI steps seems unnecessary and it's adding up to a bunch of transfer costs. This PR aims to reduce the amount of data that gets pulled from remote storage at CI time.

Minimise pulled data during CI build

---

data/raw.dvc
pyproject.toml

Closes #139 
This will make sure that the latest version of the scraper is used when creating the image.

Pin `transfermarkt-scraper` to main branch instead of tag

---

LICENSE

Some users have rightly pointed out that the project as currently no explicit license associated.
In order to be consistent with the existing license in the frontends, we are going with the CC0 license.

Add project LICENSE file

---

data/prep.dvc
data/raw.dvc
dbt/models/curated/models.yml
poetry.lock
transfermarkt_datasets/datapackage_description.md

Upgrade the `transfermarkt-scraper` module.
Relates to #191.

Upgrade `transfermarkt-scraper` module

---

.dvc/config
.github/workflows/on-push.yml
.github/workflows/on-schedule.yml
Makefile
README.md
data/README.md
data/prep.dvc
data/raw.dvc
infra/cdn/cdn.tf
infra/iam/iam.tf
infra/main.tf
poetry.lock
pyproject.toml
streamlit/01_👋_about.py

Closes #11
Enabling potential contributors to pull dvc data is key to achieve full reproducibility locally. This is currently possible, however it requires a relatively complex setup that not all users will be willing to follow.
This PR enables zero-config, public read access to dvc data.

Enable public (read) access to dvc data

---

data/prep.dvc
dbt/macros/helpers.sql
dbt/macros/io.sql
dbt/models/curated/player_valuations.sql

Relates to #215
This PR disable updates on the `player_valuations` asset.
Given that an upstream change on Transfermark is currently blocking this asset (see #215), disabling will allow for at least the rest of the assets to work normally..

Disable updates on `player_valuations` asset

---

dbt/models/base/base_game_lineups.sql
dbt/models/base/base_games.sql
dbt/models/base/sources.yml
dbt/models/curated/game_lineups.sql
dbt/models/curated/models.yml
poetry.lock
scripts/acquire.py
transfermarkt_datasets/assets/cur_game_lineups.py
transfermarkt_datasets/assets/cur_games.py

@dcaribou 
Is this approach reasonable? Are there any missing parts?
https://github.com/dcaribou/transfermarkt-scraper/pull/72

Add game lineups to dataset

---

data/prep.dvc
dbt/models/curated/models.yml

The asset has grown and naturally overcome the defined range.
Fixes build https://github.com/dcaribou/transfermarkt-datasets/actions/runs/6860101124/job/18653374229

Extend upper limit for appearances row count

---

.github/workflows/acquire-transfermarkt-api.yml

The workflow is currently setup as run on completion of acquire-transfermarkt-scraper.yml, which includes failures.
This is to skip the run in case the previous workflow fails.
Closes #249

Skip `transfermarkt-api` workflow if scraper fails

---

.github/workflows/acquire-transfermarkt-scraper.yml

Mitigates #247
There seems to be an issue with job dependency rendering in Github Actions.
For some reason it is adding a dependency between game-lineups and appearances that is not really defined in the YAML. We need to report it or ask for help here.
In any case, it does the job as it is.

Add step for acquiring `game_lineups` to GA workflow

---

data/prep.dvc
data/raw/transfermarkt-scraper.dvc
dbt/macros/io.sql
dbt/models/base/transfermarkt_scraper/base_game_lineups.sql
dbt/models/curated/game_lineups.sql
dbt/models/curated/models.yml
dbt/tests/consistent_club_ids_in_appearances.sql

Fixes #277
**Bonus**
-  Added historical data for game lineups
This is also related to https://github.com/dcaribou/transfermarkt-scraper/issues/83, although that inconsistency is affecting the `game_lineups`, rather than `appearances`.

Amend inconsistent `player_club_id`s in appearances

---

transfermarkt_datasets/assets/cur_transfers.py

I've added the 'from_club_id' and 'to_club_id' fields to the CurTransfersAsset schema. This was necessary because Streamlit was crashing due to a mismatch between the defined schema and the actual data in the CSV file. The error message indicated that these fields were present in the data but not in the schema. This update resolves the issue and allows the Streamlit app to load the transfers data correctly.

Transfer fix
